preprocessing:
  classes:
  - toxic
  - severe_toxic
  - obscene
  - threat
  - insult
  - identity_hate
  input_convertor: nn_vectorization
  input_id_column: id
  input_testset: ./data/test.csv
  input_text_column: comment_text
  input_trainset: ./data/train.csv
  random_seed: 0
  split_ratio: 0.2
  max_features: 20000
  max_text_length: 400
  maxlen: 128


training:
  batch_normalization: true
  dropout_rate: 0.5
  epochs: 1
  gradient_cliping: true
  learning_rate: 0.8
  model_name: cnn
  embedding_dim: 64
  embedding_file_input: ./data/glove.6B.100d.txt
  filters: 128
  kernel_size: 3
  hidden_dims: 256
  loss: binary_crossentropy
  optimizer: adam
  metrics: accuracy
  batch_size: 32
  pred_batch_size: 128
  verbose: 1
predict:
  output_path: ./data/submission.csv
